# Artificial Neural Network for classification


In [4]:
#importing required libraries

In [7]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score



In [5]:
# Data Pre-processing ----------------------#
# Checking the tensorflow version

In [9]:
print(tf.__version__)

2.9.1


In [11]:
# Loading the data

In [12]:
bank_data = pd.read_csv("Artificial_Neural_Network_Case_Study_data.csv")


In [13]:
# Taking  all rows and all columns in the data except the last column as X (feature matrix)
#the row numbers and customer id's are not necessary for the modelling so we get rid of and start with credit score

In [14]:
X = bank_data.iloc[:,3:-1].values
print("Independent variables are:", X)

Independent variables are: [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [15]:
#taking all rows but only the last column as Y(dependent variable)


In [16]:
y = bank_data.iloc[:, -1].values
print("Dependent variable is:", y)

Dependent variable is: [1 0 1 ... 1 1 0]


In [17]:
# Transforming the gender variable, labels are chosen randomly

In [18]:
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [19]:
# Transforming the geography column variable, labels are chosen randomly, the ct asks for argument [1] the index of the target vb


In [20]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [21]:
# Splitting the data into train and test

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [23]:
#printing the dimensions of each of those snapshots to see amount of rows and columns i each of them


In [24]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(8000, 12) (2000, 12)
(8000,) (2000,)


In [25]:
# Data Scaling/normalization of the features that will go to the NN


In [26]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


# Building the model

In [27]:
# Initializing the ANN by calling the Sequential class fromm keras of Tensorflow


In [28]:
ann = tf.keras.models.Sequential()

In [29]:
# Adding "fully connected" INPUT layer to the Sequential ANN by calling Dense class
#----------------------------------------------------------------------------------
# Number of Units = 6 and Activation Function = Rectifier

In [30]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))


In [31]:
# Adding "fully connected" SECOND layer to the Sequential AMM by calling Dense class
#----------------------------------------------------------------------------------
# Number of Units = 6 and Activation Function = Rectifier

In [32]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))



In [33]:
# Adding "fully connected" OUTPUT layer to the Sequential ANN by calling Dense class
#----------------------------------------------------------------------------------
# Number of Units = 1 and Activation Function = Sigmoid

In [34]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))


# Training the model

In [35]:
# Compiling the ANN
# Type of Optimizer = Adam Optimizer, Loss Function =  crossentropy for binary dependent variable, and Optimization is done w.r.t. accuracy


In [36]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [37]:
# Training the ANN model on training set  (fit method always the same)
# batch_size = 32, the default value, number of epochs  = 100


In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)


Epoch 1/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3921 - accuracy: 0.8370
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3920 - accuracy: 0.8381
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3923 - accuracy: 0.8381
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3923 - accuracy: 0.8378
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3923 - accuracy: 0.8370
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3921 - accuracy: 0.8384
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3921 - accuracy: 0.8361
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3919 - accuracy: 0.8374
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3919 - accuracy: 0.8374
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3920 - accura

250/250 [==============================] - 1s 4ms/step - loss: 0.3916 - accuracy: 0.8379
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3912 - accuracy: 0.8378
Epoch 83/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3910 - accuracy: 0.8389
Epoch 84/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3911 - accuracy: 0.8375
Epoch 85/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3912 - accuracy: 0.8370
Epoch 86/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3912 - accuracy: 0.8374
Epoch 87/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3911 - accuracy: 0.8374
Epoch 88/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3915 - accuracy: 0.8360
Epoch 89/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3913 - accuracy: 0.8369
Epoch 90/100
214/250 [========================>.....] - ETA: 0s - loss: 0.3870 - accuracy: 0.84

# Evaluating the Model

In [ ]:
# the goal is to use this ANN model to predict the probability of the customer leaving the bank
# Predicting the churn probability for single observations

In [ ]:
#Geography: French
#Credit Score:600
#Gender: Male
#Age: 40 years old
#Tenure: 3 years
#Balance: $60000
#Number of Products: 2
#with Credit Card
#Active member
#Estimated Salary: $50000

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)


In [ ]:
# this customer has 4% chance to leave the bank


#show the vector of predictions and real values
#probabilities

In [ ]:
y_pred_prob = ann.predict(X_test)

In [ ]:
#probabilities to binary

In [ ]:
y_pred = (y_pred_prob > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))


In [ ]:
#Confusion Matrix

In [ ]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix", confusion_matrix)
print("Accuracy Score", accuracy_score(y_test, y_pred))
